#!/bin/bash

# Detector Configurations
export DATA_PATH="$PWD/data/"            # This path will hold both dataset and output results
export LABELED_IMAGE_PATH="$PWD/images" # Path to labeled images
export CLASSES="classA, classB"         # Classes for detection
export MODEL_PATH="$PWD/model"          # This path must contain both "pipeline.config" & "model", see README
export NUM_TRAIN_STEPS=50000            # Max number of steps in training

# Environment variables passed into docker container
echo "
CLASSES=\"$CLASSES\"
NUM_TRAIN_STEPS=$NUM_TRAIN_STEPS
" >detector/env
